### PR TITLE
fix: Avoids converting a gif into a function

### LINKED ISSUE #245: Partytown tries to turn an `image/gif` response into a function
- [x] I am interested in helping provide a fix!

**Describe the bug**
I've stumbled upon [this issue](https://github.com/BuilderIO/partytown/issues/51) because we had the same problem.

Debugging it, we've discovered that the problem is that `https://googleads.g.doubleclick.net/pagead/viewthroughconversion/${SOME_NUMBER_ID}/` returns (after some redirects) a GIF.

Partytown tries to wrap it in an anonymous function, which generates the error message.

**To Reproduce**
1. Have a `doubleclick` as a Partytown script;
2. Open your webpage;
3. The error should be in the browser's console.

**Reproduction link**
I don't know how to reproduce it in a sandbox, as this script is added via GTM and I'm not lectured in Google platforms (Analytics, Ads, Tag Manager etc).

**Expected behavior**
Partytown **should not** try to run every response as Javascript, as it's possible to check the `content-type` response header

**Partytown version**
`0.6.4`

**Screenshots**
image

:point_up: Error shown in the console.

image

:point_up: Source code of the function that Partytown generated.

**Additional context**
Investigating the source files, we found that the error lies at `receiveMessageFromSandboxToWorker` arrow function from `partytown-ww-sw.js`.

Further down this block, it is possible to check the `content-type` of the response (`rsp` variable). However, I'm not exactly sure where to check it and which MIME-types to consider.

cc @leocwolter, who helped me debug
cc @orballo, who created the original issue (and might find this relevant)

### PR DESCRIPTION
**Pull request by leocwolter**
## Summary

Fixes an issue where partytown prints an error when a third party scripts requests a resource different from a script.

Closes #245

### CODE REVIEW

File: src/lib/web-worker/worker-exec.ts [hunk 1]
```diff
@@ -40,10 +41,12 @@ export const initNextScriptsInWebWorker = async (initScript: InitializeScriptDat
...
-
-        env.$currentScriptId$ = instanceId;
-        run(env, scriptContent, scriptOrgSrc || scriptSrc);
+        let responseContentType = rsp.headers.get("content-type")
+        if (!contentTypeBlocklist.some(ct => ct === responseContentType)){
+          scriptContent = await rsp.text();
+          env.$currentScriptId$ = instanceId;
+          run(env, scriptContent, scriptOrgSrc || scriptSrc);
+        }
         runStateLoadHandlers(instance!, StateProp.loadHandlers);
```
Comment (leocwolter) [inline src/lib/web-worker/worker-exec.ts:50]: Not entirely sure if this state change should be called or not

**Comment by leocwolter** [comment]
Open for ideas about how to test that since the expected behaviour is that a gif is requested with no other side effects. Is there a way to verify that using playwright? :sweat_smile: 

Also, the integration that made us find that error was Google Adsense but that should happen everytime a script inside partytown requests something other than other script.
Considering that, is it acceptable to make a test simulating that behaviour instead of trying to replicate using Google Adsense?

**Comment by adamdbradley** [comment]
This looks like a good fix, but what you also be able to add some tests to this to ensure it continues to work, and isn't breaking other tests?

File: src/lib/web-worker/worker-exec.ts [hunk 2]
```diff
@@ -27,7 +27,8 @@ export const initNextScriptsInWebWorker = async (initScript: InitializeScriptDat
   let errorMsg = '';
   let env = environments[winId];
   let rsp: Response;
-
+  let contentTypeBlocklist = ["image/gif"]
```
Comment (adamdbradley) [inline src/lib/web-worker/worker-exec.ts:30]: I think it's a good idea to validate that's javascript before we execute it. But could we do the opposite here, where we have a whitelist of content types which are valid javascript?

File: src/lib/web-worker/worker-exec.ts [hunk 3]
```diff
@@ -40,10 +41,12 @@ export const initNextScriptsInWebWorker = async (initScript: InitializeScriptDat
 
       rsp = await fetch(scriptSrc);
       if (rsp.ok) {
-        scriptContent = await rsp.text();
-
-        env.$currentScriptId$ = instanceId;
-        run(env, scriptContent, scriptOrgSrc || scriptSrc);
+        let responseContentType = rsp.headers.get("content-type")
+        if (!contentTypeBlocklist.some(ct => ct === responseContentType)){
```
Comment (adamdbradley) [inline src/lib/web-worker/worker-exec.ts:45]: This is a good idea, but rather should go with a whitelist instead of blacklist.

File: src/lib/web-worker/worker-exec.ts (hunk 2 above)
Comment (leocwolter) [reply src/lib/web-worker/worker-exec.ts:30]: My concern with using a whitelist was that maybe some request doesnt return the correct contentType  even though they are actually javascripts. If that is not something that you guys think could happen I can implement it as a white list :)

File: src/lib/web-worker/worker-exec.ts (hunk 3 above)
Comment (leocwolter) [reply src/lib/web-worker/worker-exec.ts]: Done

File: src/lib/web-worker/worker-exec.ts (hunk 2 above)
Comment (leocwolter) [reply src/lib/web-worker/worker-exec.ts]: Done

**Comment by leocwolter** [comment]
Finished the fixes and added end to end test @adamdbradley

**Comment by adamdbradley** [comment]
This is great, thanks so much for fixing this up!
